#!/bin/bash
# This script creates GitHub issues for Project Chester using GitHub CLI
# Make sure you're authenticated with `gh auth login` and inside the project repo directory

gh issue create --title "Add edit functionality for journal entries" --body "Enable inline or modal editing with save/cancel flow." --label "feature"
gh issue create --title "Implement undo/redo for journal editing" --body "Support undo and redo states during journal editing." --label "feature"
gh issue create --title "Add mood and tag metadata to journal entries" --body "Let users assign mood and emotional tags to each entry." --label "feature"
gh issue create --title "Transcribe voice-based journal input" --body "Allow users to record voice memos and transcribe to text." --label "feature,voice"
gh issue create --title "Analyze journal tone from voice input" --body "Detect emotional tone from voice pitch/pacing and store as metadata." --label "tone,AI"
gh issue create --title "Analyze tone from text journal input" --body "Use NLP to extract tone/emotion from text and store." --label "tone,AI"
gh issue create --title "Build AI chat interface for Chester" --body "Create a React-based UI for users to talk to Chester." --label "feature,AI"
gh issue create --title "Feed past journal memory into AI" --body "Allow Chester to reference previous user journal entries." --label "AI,context"
gh issue create --title "Retrieve community posts based on journal" --body "Match journal content with community posts to show related stories." --label "AI,feature"
gh issue create --title "Curate top 10 mental health frameworks" --body "Collect and rewrite CBT/DBT/grounding techniques into Chester tone." --label "dataset"
gh issue create --title "Store frameworks in Supabase" --body "Save rewritten mental health techniques in a structured Supabase table." --label "backend"
gh issue create --title "Create prompts for each framework" --body "Add warm, human prompts that Chester can ask as follow-ups." --label "content"
gh issue create --title "Add sample responses for each framework" --body "Write 1–2 Chester-style replies using each framework for training." --label "content"
gh issue create --title "Setup RAG retrieval for framework database" --body "Build RAG layer to fetch frameworks based on journal content." --label "AI,RAG"
gh issue create --title "Setup n8n Reddit → Supabase ingestion" --body "Use Reddit API to pull community posts and save to Supabase." --label "backend,n8n"
gh issue create --title "Scale Reddit ingestion with more subreddits" --body "Add more relevant mental health subreddits to n8n fetch." --label "backend,dataset"
gh issue create --title "Support delta-fetching to avoid duplicates" --body "Only fetch new Reddit posts not already in Supabase." --label "backend,n8n"
gh issue create --title "Add Reddit comments to enrich context" --body "Extend ingestion to include top-level comments." --label "dataset,n8n"
gh issue create --title "Create 5 simulated user personas" --body "Design fictional users with varying age, background, mental state." --label "dataset"
gh issue create --title "Generate journal entries per persona" --body "Write 3–5 journal entries per persona with tags and tone." --label "dataset"
gh issue create --title "Add emotion/tone tags to each persona post" --body "Label persona entries with inferred emotion + tone." --label "dataset"
gh issue create --title "Transcribe podcast/YT convos for empathy flow" --body "Find and transcribe real-life convos that show listening, story, pacing." --label "dataset,AI,tone"
gh issue create --title "Label podcast segments by emotional phase" --body "Tag conversation with labels like venting, validation, story-share." --label "AI,tagging"
gh issue create --title "Prioritize SG/MY cultural tone in conversations" --body "Include Singaporean and Malaysian voices and local expressions." --label "localization,dataset"
gh issue create --title "Design tone-based response strategy" --body "Map tone analysis (text/voice) to different Chester response flows." --label "AI,tone"
gh issue create --title "Implement \"just listening\" response style" --body "Allow Chester to respond empathetically without offering solutions." --label "AI,UX"
gh issue create --title "Add story-sharing behavior" --body "Allow Chester to softly share relevant user/community stories." --label "AI,UX"
gh issue create --title "Store all tone/emotion metadata in Supabase" --body "Save mood, tone, tags for each journal + community post." --label "backend"
gh issue create --title "Build visual tone timeline (optional)" --body "Visualize emotional trend based on journal tone over time." --label "analytics"